@api = http://localhost:3000/api/order/

### get all
GET {{api}}
Content-Type: application/json

### get all
GET {{api}}?year=2023
Content-Type: application/json

### get by id
GET {{api}}/6279a6b3-8b69-480e-84fe-9d5271c54e96
Content-Type: application/json

### post
POST {{api}}
Content-Type: application/json

{
  "order": {
    "address": "123 Main St, Springfield, USA",
    "desc": "Order of electronics including headphones and chargers.",
 	"id_delivery": "1113e23f-0528-418e-b4e4-f2ee04bc29cf",
   	"id_payment": "e22724ae-a54a-4961-937b-981b973bc4d8",
    "nameCs": "John Doe",
    "nameDelivery": "Express Logistics",
    "orderTime":  {{$timestamp}},
    "sendTime": {{$timestamp}},
    "phoneDelivery": "+1234567890",
    "priceDelivery": 4999,
    "status": "Pending",
    "totalAll": 15498,
    "totalPayment": 10499
  },
  "orderTrolley": [
	{
	  "qty_at_buy": 1,
	  "price_at_buy": 20000,
	  "id_user": "ef15593c-f129-4925-b5b0-4beced176808",
	  "id_product": "c39af8bb-6e16-49b9-a57a-c5b0849f5547"
	}
  ],
  "orderReceiver": {
	"name": "Alice Johnson",
	"address": "456 Elm Street, Springfield, USA",
	"phone": "+19876543210"
  }
}

### Update
PUT {{api}}/baffe8aa-aa6a-400f-9a8a-d2aee689cd41
Content-Type: application/json

{
  "order": {
    "address": "123 Main St, Springfield, USA update haahahhaxxx",
    "desc": "Order of electronics including headphones and chargers.",
       "id_delivery": "f14f57e4-b2c0-4429-a326-f8430395763b",
    "id_payment": "dde29f69-1fcd-49f8-8f1a-3d40a544e0c5",
    "nameCs": "John Doe update",
    "nameDelivery": "Express Logistics",
    "orderTime":  {{$timestamp}},
    "sendTime": {{$timestamp}},
    "phoneDelivery": "+1234567890",
    "priceDelivery": 4999,
    "status": "Pending",
    "totalAll": 15498,
    "totalPayment": 10499
  },
  "orderProduct": [
    	{ "id_product": "1da116c8-2d8a-4f9b-ae93-37cbad1bd83d" ,"qty": 1},
  	{ "id_product": "229b54ec-54ac-40bc-9571-90b9494bd672" ,"qty": 1}
  ],
  "orderReceiver": {
	"name": "Alice Johnson",
	"address": "456 Elm Street, Springfield, USA",
	"phone": "+19876543210"
  }
}



### delete
DELETE {{api}}/6f01f47e-acb5-41f8-85d2-f44de9fe99ea
Content-Type: application/json

{}


### seed
POST http://localhost:3000/api/seed/
Content-Type: application/json


### seed
GET http://localhost:3000/api/seed/
Content-Type: application/json
