### seed
POST http://localhost:3000/api/seed/user
Content-Type: application/json

### seed
POST http://localhost:3000/api/seed/product
Content-Type: application/json

### seed
POST http://localhost:3000/api/seed/delivery
Content-Type: application/json

### seed
POST http://localhost:3000/api/seed/payment
Content-Type: application/json

### seed
POST http://localhost:3000/api/seed/order
Content-Type: application/json
