import { Metadata } from 'next'
import './globals.css'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react';
import ReactQueryProvider from "@/app/components/Layout/ReactQueryProvider";
// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
	subsets: ['latin'],
	display: 'swap',
})

export const metadata: Metadata = {
    title: 'Index',
	description: 'Generated by create next app',
}

export default function RootLayout({children}: {
	children: ReactNode
}) {
	return (
        <html
            lang="en"
            className={ inter.className }
        >
        <body className={ "min-h-screen " }
            // data-theme={ (isDarkTheme || !isDarkTheme) ? "dark" : "light" }
        >
        <ReactQueryProvider>
            { children }
        </ReactQueryProvider>
        </body>
        </html>
    )
}
