export const exampleCompany = {
    "name": "Cv Pudji Lestari Sentosa",
    "id": 1,
    "email": "tahubaxoibupudji@ymail.com",
    "phone": "024-7691 4420",
    "address": "Jl.Diponegoro 14 Ungaran, Jawa Tengah",
    "img": "/logo.png",
    visi: [ 'text' ],
    misi: [ 'text' ]
}
export type Companys = typeof exampleCompany;

export const employeeData = {
    id: '1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '123-456-7890',
    gender: 'Male',
    dateOfBirth: new Date('1990-05-15T00:00:00Z'),
    hireDate: new Date('2015-06-01T00:00:00Z'),
    jobTitle: 'Software Engineer',
    position: 'Engineering',
    salary: 80000,
    managerId: 2,
    status: 'Active',
    address: '123 Main St, Apartment 4B',
    city: 'New York',
    postalCode: '10001',
    workTime: 'Full-time',
    notes: 'N/A',
    img: 'https://randomuser.me/api/portraits/men/1.jpg',
    country: 'USA',
    education: 'Bachelor of Science in Computer Science',
    photoKtp: '',
    photo3x4: '',
    photoIjasah: '',
    userId: 'user123',
    createdAt: new Date('2015-06-01T12:00:00Z'),
    updatedAt: new Date('2025-02-11T15:00:00Z'),
};
