export const exampleCompany = {
    "name": "John Doe",
    "id": 1,
    "email": "johndoe@example.com",
    "phone": "+1234567890",
    "address": "123 Main Street, Cityville, Country",
    "img": "https://example.com/profile.jpg"
}

export const employeeData = {
    id: '1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '123-456-7890',
    gender: 'Male',
    dateOfBirth: new Date('1990-05-15T00:00:00Z'),
    hireDate: new Date('2015-06-01T00:00:00Z'),
    jobTitle: 'Software Engineer',
    department: 'Engineering',
    salary: 80000,
    managerId: 2,
    status: 'Active',
    address: '123 Main St, Apartment 4B',
    city: 'New York',
    postalCode: '10001',
    employmentType: 'Full-time',
    notes: 'N/A',
    img: 'https://randomuser.me/api/portraits/men/1.jpg',
    country: 'USA',
    education: 'Bachelor of Science in Computer Science',
    photoKtp: '',
    photo3x4: '',
    photoIjasah: '',
    userId: 'user123',
    createdAt: new Date('2015-06-01T12:00:00Z'),
    updatedAt: new Date('2025-02-11T15:00:00Z'),
};