import { TPaymentCreate, TPaymentDB } from "@/interface/entity/payment.model"

export const examplePayment: TPaymentCreate = {
    // id        : "kosong",  // ID can be autogenerated or provided dynamically
    type: "Credit Card", // Example payment method type
    address: "123 Main St, Springfield, IL", // Billing address for payment
    desc: "Payment for order #12345", // Description of the payment
    accounting: "Transaction #98765", // Reference for accounting or tracking purposes
    phone: "+6234567890", // Contact phone number associated with the payment
    img: "https://example.com/payment-image.jpg", // Image URL related to payment method (optional)
    name: "John Doe", // Name of the person making the payment
}
export const formBank: Record<keyof TPaymentDB, any> = {
    phone: "No Telephone Perusahaan",
    name: "Nama Bank",
    accounting: "No Rekening",
    id: "123_bank",
    address: "Lokasi Bank",
    type: "Jenis Bank",
    desc: "Keterangan",
    img: "URL Gambar Logo perusahaan ",
    created_at: new Date(),
    updated_at: new Date(),
}

export const paymentExample: TPaymentDB = {
    "id": "dde29f69-1fcd-49f8-8f1a-3d40a544e0c5",
    "name": "mandiri",
    "phone": "082123123123",
    "accounting": "012312391231",
    "address": "Semrang",
    "type": "Kredit",
    "img": "https://logowik.com/content/uploads/images/cash2548.jpg",
    "desc": "orak jelas",
    "created_at": new Date(),
    "updated_at": new Date()
}

//i want get a key only
// const myKeyIsName:keyof typeof paymentExample='xxx'
// const myKeyIsPhone:keyof paymentExample='phone'

